# Generated by Django 5.1.5 on 2025-07-07 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["user", "movie"], name="interaction_user_id_7ecddd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interaction",
            unique_together={("user", "movie")},
        ),
    ]
