# Generated by Django 5.1.5 on 2025-07-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='bio',
            new_name='surname',
        ),
    ]
